name: Extract Secret

on:
  push:
    branches:
      - main

jobs:
  extract-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract and Print Secret
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
      run: |
        echo "My Secret (visible): $MY_SECRET"
