name: Print_Values_secrets
on:
  push:
    branches:
      - main

jobs:
  print-values:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print GitHub Secret and Variable
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
        MY_VARIABLE: ${{ vars.MY_VARIABLE }}
      run: |
        echo "My Secret: $MY_SECRET"
        echo "My Variable: $MY_VARIABLE"
        echo "My Secret (visible): $MY_SECRET"
        run: cat $MY_SECRET"
