name: Extract Secrets

on:
  push:
    branches:
      - main

jobs:
  extract-and-print-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract and Print Secret
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
        MY_VARIABLE: ${{ vars.MY_VARIABLE }}
      run: |
        echo "Extracted Secret (visible): $MY_SECRET"
        echo "Extracted Variable: $MY_VARIABLE"
